#! /bin/bash
#--------------------------------------
# lab3
#--------------------------------------

echo "compiling Lawn.java"
javac Lawn.java >& Lawn-errs
echo "running Lawn.class"
java Lawn < Lawn-in > Lawn-out
echo "deleting the file Lawn.class"
rm Lawn.class

